version: '2.2'

services:
  golang:
    image: golang:1.20.4
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    volumes:
      - ./:/go/src/github.com/satyamvatstyagi/ELKLogGenerator
      - ./logs/:/logs/
    working_dir: /go/src/github.com/satyamvatstyagi/ELKLogGenerator
    command: go run main.go
    ports:
      - 8080:8080

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.0
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/logs/

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-s",
          "-f",
          "http://localhost:9200/_cat/health"
        ]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-s",
          "-f",
          "http://localhost:5601/api/status"
        ]
      interval: 3s
      timeout: 3s
      retries: 50
    ports:
      - 5601:5601
